# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "inoffical Bitbucket.org command line tool"
  homepage "github.com/craftamap/bb"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/craftamap/bb/releases/download/v0.6.0/bb_Darwin_arm64.tar.gz"
      sha256 "d368725694ace66afd073db73a773b42331a5b7143c66d87f4b06983e999a022"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/craftamap/bb/releases/download/v0.6.0/bb_Darwin_x86_64.tar.gz"
      sha256 "61bd2784fc734cb34e99bf54cc5f0d83a3e6a0a86c3e56d06d18865b29652461"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftamap/bb/releases/download/v0.6.0/bb_Linux_arm64.tar.gz"
      sha256 "cd9fd58e8276c37ea160e5ee7619d9e56296f1193dfb0bb2b2d391817f419977"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/craftamap/bb/releases/download/v0.6.0/bb_Linux_x86_64.tar.gz"
      sha256 "4b7bd7f9f1812ff879016479fd3b676c884e82053478b100a3d2bcdbbb735880"

      def install
        bin.install "bb"
      end
    end
  end
end
