# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "inoffical Bitbucket.org command line tool "
  homepage "https://siegelfabian.de/"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/craftamap/bb/releases/download/v0.2.1/bb_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "bad4623b4f9ce84a139bac1b6e97bf06e69195b1f8e27f43e12ddf08c8af1b06"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/craftamap/bb/releases/download/v0.2.1/bb_0.2.1_Linux_x86_64.tar.gz"
    sha256 "e8424dba9226b12747f4960d9690db55a73cb74566cf683d9caf3b7fb1f3e94d"
  end

  def install
    bin.install "bb"
  end
end
